[package]
name = "ebpm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fs_extra = "1.2.0"
colored = "2"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
zip = "2.2.2"
